name: 'Main'

on:
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: windows-latest
    name: Build and Package
    permissions:
      packages: write
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "Run scripts and package extension"
      working-directory: '${{ github.workspace }}\tasks\akeylesstask'
      run: |
        # prep code
        npm run restore
        npm run format
        npm run lint 
        # npm run test
        npm i -g tfx-cli    # tfx CLI docs https://github.com/microsoft/tfs-cli/blob/master/docs/extensions.md
        npm run package     # Create VSIX
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"

    - uses: actions/upload-artifact@v4
      with:
        name: lancelotsoftware.akeyless-secrets
        path: "**/*.vsix"
        retention-days: 30

    # ************************| GITHUB RELEASE |************************ #

    # - name: Generate version number with date and workflow Run Number
    #   id: version-creator
    #   run: |
    #     $buildDay = Get-Date -Format "yyyy.Mdd"
    #     $runNumber = "$env:GITHUB_RUN_NUMBER"
    #     $ver = $buildDay + "." + $runNumber + ".0"
    #     echo "APP_VERSION=$ver" >> "$env:GITHUB_ENV"

    # - name: Create GitHub Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    #   with:
    #     tag_name: "build.${{github.run_number}}"
    #     release_name: "Akeyless AzDO Extensions (build.${{github.run_number}})"
    #     draft: false
    #     prerelease: true

    # - name: Uploading Release Asset
    #   id: upload-release-asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    #   with:
    #     upload_url: ${{steps.create_release.outputs.upload_url}}
    #     asset_path: "${{github.workspace}}/*.vsix"
    #     asset_name: lancelotsoftware.akeylessExtensionsAzdo.vsix
    #     asset_content_type: application/zip
